run: # https://golangci-lint.run/usage/configuration/#run-configuration
  go: '1.22'
  timeout: 3m
linters-settings: # https://golangci-lint.run/usage/configuration/#linters-settings-configuration
  dupl:
    # Tokens count to trigger issue.
    threshold: 150
  funlen:
    lines: 200
    statements: 200
  stylecheck: # https://golangci-lint.run/usage/linters/#stylecheck
    checks: [ "-ST1000" ]
  gocyclo:
    min-complexity: 36
  gofmt:
    # Simplify code: gofmt with `-s` option.
    # Default: true
    simplify: true
    # Apply the rewrite rules to the source before reformatting.
    # https://pkg.go.dev/cmd/gofmt
    # Default: []
    rewrite-rules:
      - pattern: 'interface{}'
        replacement: 'any'
      - pattern: 'a[b:len(a)]'
        replacement: 'a[b:]'
  revive:
    enable-all-rules: false
    rules:
      - name: empty-lines
      - name: use-any
      - name: struct-tag
      - name: context-as-argument
      - name: context-keys-type
      - name: error-return
      - name: error-naming
      - name: exported
        disabled: true
      - name: if-return
      - name: increment-decrement
      - name: var-declaration
      - name: package-comments
        disabled: true
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: superfluous-else
      - name: unused-parameter
        disabled: true
      - name: unreachable-code
      - name: redefines-builtin-id
linters: # https://golangci-lint.run/usage/linters/
  disable-all: true
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - copyloopvar
    - dogsled
    - dupl
    - errcheck
    - fatcontext
    - funlen
    - gci
    - gocyclo
    - gocritic
    - gofmt
    - goheader
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - prealloc
    - misspell
    - mirror
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unused
    - whitespace
    - revive
    - protogetter
    - tagalign

issues: # https://golangci-lint.run/usage/configuration/#issues-configuration
  exclude-dirs:
    - data/ent
  exclude-files:
    - service/graphql/generated.go
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - funlen
        - gosec
        - gocritic
        - errcheck