// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-keg/simple/biz"
	"github.com/go-keg/simple/conf"
	"github.com/go-keg/simple/data"
	"github.com/go-keg/simple/job"
	"github.com/go-keg/simple/schedule"
	"github.com/go-keg/simple/server"
	"github.com/go-keg/simple/service/graphql"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "github.com/go-keg/simple/data/ent/runtime"
)

// Injectors from wire.go:

func initApp(logger log.Logger, config *conf.Config) (*kratos.App, func(), error) {
	client, err := data.NewEntClient(config)
	if err != nil {
		return nil, nil, err
	}
	accountUseCase := biz.NewAccountUseCase(config)
	executableSchema := graphql.NewSchema(logger, client, accountUseCase)
	httpServer := server.NewHTTPServer(config, logger, client, executableSchema)
	jobJob := job.NewJob(logger, client, config)
	syncProducer, err := data.NewKafkaProducer(config)
	if err != nil {
		return nil, nil, err
	}
	daily := schedule.NewDaily(client, syncProducer)
	scheduleSchedule := schedule.NewSchedule(logger, client, daily)
	app := newApp(logger, httpServer, jobJob, scheduleSchedule)
	return app, func() {
	}, nil
}
